# Generated by Django 4.1.5 on 2023-02-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0008_lang_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lang',
            name='iso',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
