# Generated by Django 4.1.5 on 2023-03-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0009_remove_country_id_remove_lang_id_alter_country_iso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='country',
            name='langs',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Lang',
        ),
    ]
