# Generated by Django 4.1.5 on 2023-03-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0013_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
