# Generated by Django 4.1.5 on 2023-03-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0014_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='root',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
