# Generated by Django 4.1.5 on 2023-03-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xxx', '0015_remove_genre_parent_remove_node_root_delete_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OneDoc',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xxx.doc',),
        ),
        migrations.CreateModel(
            name='TwoDoc',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('xxx.doc',),
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=20)),
                ('one', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one', to='xxx.onedoc')),
                ('two', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='xxx.twodoc')),
            ],
        ),
    ]
