# Generated by Django 4.1.5 on 2023-03-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0016_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
