# Generated by Django 4.1.5 on 2023-03-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0017_doc_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='text',
        ),
    ]
