# Generated by Django 4.1.5 on 2023-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0018_remove_doc_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
