# Generated by Django 4.1.5 on 2023-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0019_doc_text_alter_doc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('res_data', models.JSONField()),
            ],
        ),
    ]
