# Generated by Django 4.1.5 on 2023-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0020_domaincheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaincheck',
            name='check_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domaincheck',
            name='id_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domaincheck',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='domaincheck',
            name='res_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
