# Generated by Django 4.1.5 on 2023-03-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0021_domaincheck_check_id_domaincheck_id_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaincheck',
            name='check_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
