# Generated by Django 4.1.5 on 2023-03-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0023_alter_domaincheck_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainCheck',
        ),
        migrations.RemoveField(
            model_name='main',
            name='one',
        ),
        migrations.RemoveField(
            model_name='main',
            name='two',
        ),
        migrations.DeleteModel(
            name='OneDoc',
        ),
        migrations.DeleteModel(
            name='TwoDoc',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
