# Generated by Django 4.1.5 on 2023-07-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0027_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('orig_img', models.ImageField(blank=True, upload_to='')),
                ('thumb', models.ImageField(blank=True, upload_to='')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxx.domain')),
            ],
            options={
                'unique_together': {('domain', 'image_url')},
            },
        ),
    ]
