# Generated by Django 4.1.5 on 2023-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxx', '0029_siteimages_thumb_compress_alter_siteimages_orig_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='examples')),
            ],
        ),
    ]
